#:import TransitionClass kivy.uix.screenmanager.SlideTransition

<TextInput>:
    use_bubble: False

<YesNoContent>:
    orientation: 'vertical'
    Label:
        background_color: 0,0,0,0.4
        text: root.text
        text_size: root.width, root.height * 0.7
        valign: 'middle'

    GridLayout:
        cols: 2
        size_hint: 1, 0.2
        Button:
            text: 'Yes'
            on_release: root.dispatch('on_answer','y')
        Button:
            text: 'No'
            on_release: root.dispatch('on_answer','n')


<YesNoQuitContent>:
    orientation: 'vertical'
    Label:
        text: root.text
        text_size: root.width, root.height * 0.7
        valign: 'middle'

    GridLayout:
        cols: 3
        size_hint: 1, 0.2
        Button:
            text: 'Yes'
            on_release: root.dispatch('on_answer','y')
        Button:
            text: 'No'
            on_release: root.dispatch('on_answer','n')
        Button:
            text: 'Quit'
            on_release: root.dispatch('on_answer','q')


<StringContent>:
    orientation: 'vertical'
    Label:
        text: root.text
        text_size: root.width, root.height * 0.7
        valign: 'middle'

    GridLayout:
        cols: 2
        size_hint: 1, 0.2
        TextInput:
            id: chosen_answer
            text: ''
            hint_text: 'enter your choice'
            use_bubble: True
        Button:
            size_hint: None, 1
            width: 100
            text: 'Enter'
            on_release: root.dispatch('on_answer', chosen_answer.text)


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: 0.1
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.selection)

<UrlDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        TextInput:
            id: urlinput
            hint_text: 'http://testphp.vulnweb.com/search.php?test=hi'
            text: 'http://testphp.vulnweb.com/search.php?test=hi'
            use_bubble: True

        BoxLayout:
            size_hint_y: 0.1
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "OK"
                on_release: root.load(urlinput.text)

<TargetDialog>:
    orientation: "vertical"
    padding: [0, 50, 0, 50]
    spacing: 30

    Button:
        id: target_url_button
        size_hint_x: 0.6
        pos_hint: {'x': 0.2}
        text: 'URL'
        on_press: root.url_dialog()

    Button:
        id: target_logfile_button
        size_hint_x: 0.6
        pos_hint: {'x': 0.2}
        text: 'logfile'
        on_press: root.log_dialog()

    Button:
        id: target_bulkfile_button
        size_hint_x: 0.6
        pos_hint: {'x': 0.2}
        text: 'bulk file'
        on_press: root.bulk_dialog()

    Button:
        id: target_requestfile_button
        size_hint_x: 0.6
        pos_hint: {'x': 0.2}
        text: 'request file'
        on_press: root.request_dialog()

    Button:
        id: target_inifile_button
        size_hint_x: 0.6
        pos_hint: {'x': 0.2}
        text: 'INI config'
        on_press: root.ini_dialog()


<FileChooseButton>:
    text: 'Choose a file...'
    size_hint: None, 1
    width: self.parent.width - 150
    pos_hint: {'x': 0, 'y': 0}
    # pos: -100,-100
    # height: self.line_height


<LogMessage>:
    size_hint: 1, None
    height: self.texture_size[1]
    font_size: '12sp'
    text_size: self.width, None


<Sqlmapchik>:
    orientation: 'vertical'
    manager: manager
    menu_screen: menu_screen
    log_screen: log_screen
    scrolled_window: scrolled_window

    ScreenManager:
        id: manager
        transition: TransitionClass()

        Screen:
            id: menu_screen
            name: 'menu'
            BoxLayout:
                orientation: 'vertical'
                spacing: 30
                padding: [0, 50, 0, 50]

                Image:
                    size_hint: 0.6, 0.5
                    pos_hint: {'x': 0.2}
                    source: 'chik_res/logo.png'

                Button:
                    id: go_button
                    size_hint: 0.6, 0.3
                    pos_hint: {'x': 0.2}
                    text: 'Start scan'
                    on_press: root.launch_dialog()#app.main(target_url.text, additional_flags.text)

                Button:
                    id: open_options_button
                    size_hint: 0.6, 0.2
                    pos_hint: {'x': 0.2}
                    text: 'Options'
                    on_press: app.open_settings()

        Screen:
            name: 'log'
            BoxLayout:
                id: log_screen
                orientation: 'vertical'

                ScrollView:
                    size_hint: 1, 1
                    scroll_y: 0
                    do_scroll_x: False

                    GridLayout:
                        id: scrolled_window
                        # orientation: 'vertical'
                        cols: 1
                        size_hint_y: None
                        height: self.minimum_height
